### ISSUE TITLE
Module build failed. Error: Couldn't find preset "@babel/preset-env"

### ISSUE THREAD

**Issue by jamland** [bbhlondon/cra-append-sw#1]
Hi!

I'm trying to run `react-scripts build && cra-append-sw ./src/custom-sw.js` but got this this error output. 
I believe I have installed `babel` and `babel-preset-env`. Any suggestions what this might be?

```
(node:39491) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Hash: e6507254b0b91c634262
Version: webpack 3.8.1
Time: 595ms
    Asset    Size  Chunks             Chunk Names
bundle.js  1.9 kB       0  [emitted]  main
   [0] ./src/custom-sw.js 1.43 kB {0} [built] [failed] [1 error]

ERROR in ./src/custom-sw.js
Module build failed: Error: Couldn't find preset "@babel/preset-env" relative to directory "/Users/Andy/Sites/repository/app/src"
    at /Users/Andy/Sites/repository/app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/Andy/Sites/repository/app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/Andy/Sites/repository/app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/Andy/Sites/repository/app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/Andy/Sites/repository/app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/Andy/Sites/repository/app/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/Andy/Sites/repository/app/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/Andy/Sites/repository/app/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/Andy/Sites/repository/app/node_modules/babel-loader/lib/index.js:49:20)
(node:39491) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by marcelkornblum** [comment]
Hi @jamland thanks for the report. I can replicate it here. It looks as though we have dependency bleed between this project and the project we were working on that made us build this - sorry about that!

I haven't got time to dig into the specifics to fix it right now, but if you're happy for your SW additions not to be parsed, you can add the `-s` parameter for now and it will work for you.

For example `react-scripts build && cra-append-sw -s ./src/custom-sw.js` works for me.

@tszarzynski when you get a moment could you take a look please?

**Comment by DanPen** [comment]
I have the same issue. Why does Babel have to be so confusing?

**Comment by tszarzynski** [comment]
The latest release (2.1.0) fixes the problem
